#
# Copyright (c) 2025 codingas.com
# Licensed under the Apache License, Version 2.0.
# See the LICENSE file for details.
#

simulator:
  mode: normal
  request-log-capacity: 100

server:
  port: 9090
