-- ==========================================
-- V37: ChannelEndpoint 实体
-- 1. 创建 channel_endpoints 表
-- 2. 迁移 channels 表的 endpoint_url/protocol 数据到 channel_endpoints
-- 3. 删除 channels 表的 endpoint_url/protocol 列
-- ==========================================

-- 1. 创建 channel_endpoints 表
CREATE TABLE channel_endpoints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id BIGINT NOT NULL,
    protocol VARCHAR(32) NOT NULL,
    endpoint_url VARCHAR(512) NOT NULL,
    state VARCHAR(16) DEFAULT 'ACTIVE',
    created_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_channel_endpoint UNIQUE (channel_id, protocol)
);

CREATE INDEX idx_channel_endpoints_channel ON channel_endpoints(channel_id);
CREATE INDEX idx_channel_endpoints_protocol ON channel_endpoints(protocol);

-- 2. 迁移现有数据
INSERT INTO channel_endpoints (channel_id, protocol, endpoint_url, state, created_at, updated_at)
SELECT id, protocol, endpoint_url, 'ACTIVE', created_at, updated_at
FROM channels
WHERE endpoint_url IS NOT NULL;

-- 3. 删除 channels 表的 endpoint_url 和 protocol 列
ALTER TABLE channels DROP COLUMN endpoint_url;
ALTER TABLE channels DROP COLUMN protocol;
