--
-- Copyright © 2025-2026 codingas.com
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--
-- ==========================================
-- V37: ChannelEndpoint 实体
-- 1. 创建 channel_endpoints 表
-- ==========================================

-- 1. 创建 channel_endpoints 表
CREATE TABLE channel_endpoints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id BIGINT NOT NULL,
    protocol VARCHAR(32) NOT NULL,
    endpoint_url VARCHAR(512) NOT NULL,
    state VARCHAR(16) DEFAULT 'ACTIVE',
    created_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_channel_endpoint UNIQUE (channel_id, protocol)
);

CREATE INDEX idx_channel_endpoints_channel ON channel_endpoints(channel_id);
CREATE INDEX idx_channel_endpoints_protocol ON channel_endpoints(protocol);

-- 注：channels 表的 endpoints JSON 列和 protocol 列由应用层 MetadataSyncService 处理
-- 不在此迁移中做列变更，避免与 JPA ddl-auto 冲突