-- V39: 创建调用日志表
CREATE TABLE call_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id VARCHAR(64) NOT NULL,
    user_id BIGINT,
    model VARCHAR(128),
    channel_id BIGINT,
    channel_endpoint_id BIGINT,
    inbound_protocol VARCHAR(32),
    upstream_protocol VARCHAR(32),
    duration_ms BIGINT,
    success BOOLEAN,
    input_tokens INTEGER,
    output_tokens INTEGER,
    error_message VARCHAR(1024),
    called_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_call_logs_trace_id ON call_logs(trace_id);
CREATE INDEX idx_call_logs_user_id ON call_logs(user_id);
CREATE INDEX idx_call_logs_channel_id ON call_logs(channel_id);
CREATE INDEX idx_call_logs_called_at ON call_logs(called_at);
