-- V4__init_llm_data.sql
-- 初始化大模型 Provider、API Key 和 Model 数据
--
-- 注意：数据初始化已迁移到 DataInitializer（仅 local/dev 环境）
-- 此脚本保留为空，以保持 Flyway 版本号连续
--
-- 生产环境的数据初始化应通过以下方式完成：
-- 1. 管理员通过管理界面添加 Provider 和 Model
-- 2. 或通过专门的迁移脚本导入
