--
-- Copyright © 2025-2026 codingas.com
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--
-- V4__init_llm_data.sql
-- 初始化大模型 Provider、API Key 和 Model 数据
--
-- 注意：数据初始化已迁移到 DataInitializer（仅 local/dev 环境）
-- 此脚本保留为空，以保持 Flyway 版本号连续
--
-- 生产环境的数据初始化应通过以下方式完成：
-- 1. 管理员通过管理界面添加 Provider 和 Model
-- 2. 或通过专门的迁移脚本导入
