--
-- Copyright © 2025-2026 codingas.com
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--
-- Task 3: 应用-渠道授权关联表新增 priority 列
-- 转移顺序由全局 ModelInstance.priority 改为应用级 ApplicationChannel.priority，
-- 同一渠道对不同应用可有不同转移顺序。priority 为 NULL 表示未配置，PriorityRouter 回退默认值 100。
ALTER TABLE application_channels ADD COLUMN priority INT NULL;
