#
# Copyright © 2025-2026 codingas.com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Unix 平台 filter：将 conf/template 中的 ${pkg.logFolder} 替换为 ${pkg.unixLogFolder}
# pkg.unixLogFolder 在 gateway-boot/pom.xml 的 pkg profile 定义为 /var/log/${pkg.name}
pkg.logFolder=${pkg.unixLogFolder}
