#
# Copyright (c) 2025 codingas.com
# Licensed under the Apache License, Version 2.0.
# See the LICENSE file for details.
#

# Unix 平台 filter：将 conf/template 中的 ${pkg.logFolder} 替换为 ${pkg.unixLogFolder}
# pkg.unixLogFolder 在 gateway-boot/pom.xml 的 pkg profile 定义为 /var/log/${pkg.name}
pkg.logFolder=${pkg.unixLogFolder}
