package com.codingas.gateway.infrastructure.migration;

import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.util.StreamUtils;

import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.atomic.AtomicLong;
import java.util.stream.Collectors;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.fail;

/**
 * V52 Team→Application 数据迁移测试
 *
 * <p>验证 D7（幂等）/ D9（授权不丢失、不放大）迁移语义：</p>
 * <ul>
 *   <li>每个 Team 生成对应 Application（code = 'team-' || id），TeamChannel 平移为 ApplicationChannel</li>
 *   <li>单 Team 用户 Key 回填到对应 Team 的 Application</li>
 *   <li>多 Team / 无 Team 用户 Key 归 migration-default，多 Team 渠道集取并集</li>
 *   <li>重复执行 V52 不产生重复数据（幂等）</li>
 * </ul>
 *
 * <p>实现方式：Flyway 在 H2（PostgreSQL 兼容模式）上执行到 V50 建立源表（teams/user_teams/
 * team_channels/user_api_keys，与生产真实 schema 一致）；V51 因使用 MySQL 方言（AUTO_INCREMENT/
 * UNIQUE KEY）在 H2 上不可执行且本任务禁止修改，故 applications/application_channels 与
 * user_api_keys.application_id 由本测试以 H2/PostgreSQL 兼容 DDL 手工建立（列定义与 V51 一致）。
 * 随后植入源数据，手动执行 V52 SQL 断言迁移结果。V52 由测试手动执行（非 Flyway 触发），
 * 便于 RED/幂等等场景验证。每个测试方法使用独立内存库，互不干扰。</p>
 */
class TeamToApplicationMigrationTest {

    /** V52 迁移脚本 classpath 路径 */
    private static final String V52_PATH = "db/migration/V52__migrate_team_to_application.sql";

    /** 每个测试方法分配独立内存库，避免状态泄漏 */
    private static final AtomicLong DB_SEQ = new AtomicLong();

    private JdbcTemplate jdbc;

    @BeforeEach
    void setUp() {
        // 1. 每个测试方法使用独立 H2（PostgreSQL 兼容模式）内存库；DB_CLOSE_DELAY=-1 保证连接间共享同一库
        DriverManagerDataSource ds = new DriverManagerDataSource();
        ds.setUrl("jdbc:h2:mem:v52test-" + DB_SEQ.incrementAndGet() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        ds.setUsername("sa");
        ds.setPassword("");

        // 2. Flyway 仅迁移到 V50（V1..V50 均为 H2 兼容；V51 因 MySQL 方言跳过，由下方手工建表替代）
        Flyway.configure()
                .dataSource(ds)
                .locations("classpath:db/migration")
                .target("50")
                .load()
                .migrate();

        // 3. 手工建立 V51 的 applications / application_channels 表与 user_api_keys.application_id 列
        //    （列定义与 V51 一致，但使用 H2/PostgreSQL 兼容的 IDENTITY/CONSTRAINT 语法）
        createApplicationSchema(ds);

        this.jdbc = new JdbcTemplate(ds);
        seedSourceData();
    }

    /**
     * 建立 applications / application_channels 表并为 user_api_keys 挂 application_id 列
     *
     * <p>等价于 V51 的 DDL，但改用 H2/PostgreSQL 兼容语法（GENERATED BY DEFAULT AS IDENTITY
     * 替代 AUTO_INCREMENT，CONSTRAINT ... UNIQUE 替代 UNIQUE KEY）。</p>
     */
    private void createApplicationSchema(javax.sql.DataSource ds) {
        JdbcTemplate t = new JdbcTemplate(ds);
        t.execute("CREATE TABLE applications ("
                + "  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                + "  code VARCHAR(64) NOT NULL UNIQUE,"
                + "  name VARCHAR(128) NOT NULL,"
                + "  description VARCHAR(512),"
                + "  state VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',"
                + "  resilience_profile_id BIGINT,"
                + "  quota_budget_id BIGINT,"
                + "  dashboard_id BIGINT,"
                + "  created_by BIGINT,"
                + "  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,"
                + "  updated_by BIGINT,"
                + "  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP"
                + ")");
        t.execute("CREATE INDEX idx_applications_code ON applications(code)");
        t.execute("CREATE TABLE application_channels ("
                + "  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                + "  application_id BIGINT NOT NULL,"
                + "  channel_id BIGINT NOT NULL,"
                + "  created_by BIGINT,"
                + "  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,"
                + "  updated_by BIGINT,"
                + "  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,"
                + "  CONSTRAINT uk_app_channel UNIQUE (application_id, channel_id)"
                + ")");
        t.execute("CREATE INDEX idx_app_channels_app ON application_channels(application_id)");
        t.execute("ALTER TABLE user_api_keys ADD COLUMN application_id BIGINT");
    }

    /**
     * 植入源数据：3 用户 / 3 团队 / 4 团队渠道 / 3 Key
     *
     * <ul>
     *   <li>u1 单团队(t10)：Key k1001 → 应回填 team-10</li>
     *   <li>u2 多团队(t20,t30)：Key k1002 → 应归 migration-default，渠道集 {200,300}</li>
     *   <li>u3 无团队：Key k1003 → 应归 migration-default，渠道集空</li>
     *   <li>团队渠道：t10→{100,101}，t20→{200}，t30→{300}</li>
     * </ul>
     */
    private void seedSourceData() {
        // users（V10 已将 status 重命名为 state）
        jdbc.update("INSERT INTO users (id, username, state) VALUES (1, 'single-team-user', 'ACTIVE')");
        jdbc.update("INSERT INTO users (id, username, state) VALUES (2, 'multi-team-user', 'ACTIVE')");
        jdbc.update("INSERT INTO users (id, username, state) VALUES (3, 'no-team-user', 'ACTIVE')");

        // teams（state 为小写 'active'，迁移后应映射为大写 'ACTIVE'）
        jdbc.update("INSERT INTO teams (id, name, description, state) VALUES (10, '团队A', '描述A', 'active')");
        jdbc.update("INSERT INTO teams (id, name, description, state) VALUES (20, '团队B', '描述B', 'active')");
        jdbc.update("INSERT INTO teams (id, name, description, state) VALUES (30, '团队C', '描述C', 'active')");

        // user_teams
        jdbc.update("INSERT INTO user_teams (user_id, team_id, role) VALUES (1, 10, 'owner')");
        jdbc.update("INSERT INTO user_teams (user_id, team_id, role) VALUES (2, 20, 'owner')");
        jdbc.update("INSERT INTO user_teams (user_id, team_id, role) VALUES (2, 30, 'member')");

        // team_channels
        jdbc.update("INSERT INTO team_channels (team_id, channel_id) VALUES (10, 100)");
        jdbc.update("INSERT INTO team_channels (team_id, channel_id) VALUES (10, 101)");
        jdbc.update("INSERT INTO team_channels (team_id, channel_id) VALUES (20, 200)");
        jdbc.update("INSERT INTO team_channels (team_id, channel_id) VALUES (30, 300)");

        // user_api_keys（application_id 初始为 NULL）
        jdbc.update("INSERT INTO user_api_keys (id, user_id, key_hash, key_prefix, name, deleted) VALUES (1001, 1, 'hash-k1', 'sk-k1-', '单团队Key', FALSE)");
        jdbc.update("INSERT INTO user_api_keys (id, user_id, key_hash, key_prefix, name, deleted) VALUES (1002, 2, 'hash-k2', 'sk-k2-', '多团队Key', FALSE)");
        jdbc.update("INSERT INTO user_api_keys (id, user_id, key_hash, key_prefix, name, deleted) VALUES (1003, 3, 'hash-k3', 'sk-k3-', '无团队Key', FALSE)");
    }

    /**
     * 读取并执行 V52 迁移脚本
     *
     * <p>RED 状态下脚本不存在，本方法会令测试失败并给出明确原因。</p>
     */
    private void runV52() {
        ClassPathResource resource = new ClassPathResource(V52_PATH);
        if (!resource.exists()) {
            fail("V52 迁移脚本未找到: " + V52_PATH + "（RED：迁移脚本尚未创建）");
            return;
        }
        String sql;
        try {
            sql = StreamUtils.copyToString(resource.getInputStream(), StandardCharsets.UTF_8);
        } catch (Exception e) {
            throw new RuntimeException("读取 V52 失败", e);
        }
        // 移除 -- 行注释后按分号拆分逐条执行（V52 脚本语句内无嵌入分号）
        String cleaned = Arrays.stream(sql.split("\n"))
                .filter(line -> !line.trim().startsWith("--"))
                .collect(Collectors.joining("\n"));
        for (String stmt : cleaned.split(";")) {
            String trimmed = stmt.trim();
            if (!trimmed.isEmpty()) {
                jdbc.update(trimmed);
            }
        }
    }

    /** 查询指定 code 的 Application id */
    private Long appIdByCode(String code) {
        return jdbc.queryForObject(
                "SELECT id FROM applications WHERE code = ?", Long.class, code);
    }

    /** 查询指定 Application code 下的渠道集合 */
    private Set<Long> channelsOfApp(String appCode) {
        return jdbc.queryForList(
                "SELECT ac.channel_id FROM application_channels ac "
                        + "JOIN applications a ON a.id = ac.application_id WHERE a.code = ?",
                Long.class, appCode).stream().collect(Collectors.toSet());
    }

    @Test
    @DisplayName("migration-default 兜底应用存在")
    void migrationDefaultAppExists() {
        runV52();
        assertThat(appIdByCode("migration-default")).isNotNull();
    }

    @Test
    @DisplayName("每个 Team 生成对应 Application，继承 name/description，state 大写化为 ACTIVE")
    void teamToApplicationMapping() {
        runV52();

        Map<String, Object> app10 = jdbc.queryForMap(
                "SELECT code, name, description, state FROM applications WHERE code = 'team-10'");
        assertThat(app10.get("code")).isEqualTo("team-10");
        assertThat(app10.get("name")).isEqualTo("团队A");
        assertThat(app10.get("description")).isEqualTo("描述A");
        assertThat(app10.get("state")).isEqualTo("ACTIVE");

        // 验证 team-20 / team-30 也已生成
        assertThat(appIdByCode("team-20")).isNotNull();
        assertThat(appIdByCode("team-30")).isNotNull();
    }

    @Test
    @DisplayName("TeamChannel 1:1 平移为 ApplicationChannel，授权集合相等")
    void teamChannelFlattenedToApplicationChannel() {
        runV52();

        // team-10 原渠道集 {100,101} == team-10 App 渠道集
        assertThat(channelsOfApp("team-10")).isEqualTo(Set.of(100L, 101L));
        assertThat(channelsOfApp("team-20")).isEqualTo(Set.of(200L));
        assertThat(channelsOfApp("team-30")).isEqualTo(Set.of(300L));

        // 按 team 聚合断言：每个 team 的 team_channels 集合 == 对应 application_channels 集合
        List<Map<String, Object>> teamRows = jdbc.queryForList(
                "SELECT t.id AS team_id FROM teams t");
        for (Map<String, Object> row : teamRows) {
            long teamId = ((Number) row.get("team_id")).longValue();
            Set<Long> teamChannels = jdbc.queryForList(
                    "SELECT channel_id FROM team_channels WHERE team_id = ?",
                    Long.class, teamId).stream().collect(Collectors.toSet());
            Set<Long> appChannels = channelsOfApp("team-" + teamId);
            assertThat(appChannels).as("team-%s 授权集合应与原 team_channels 一致", teamId)
                    .isEqualTo(teamChannels);
        }
    }

    @Test
    @DisplayName("单 Team 用户 Key 回填到对应 Team 的 Application")
    void singleTeamUserKeyBackfilled() {
        runV52();

        Long kApp = jdbc.queryForObject(
                "SELECT application_id FROM user_api_keys WHERE id = 1001", Long.class);
        assertThat(kApp).isEqualTo(appIdByCode("team-10"));
    }

    @Test
    @DisplayName("多 Team 用户 Key 归 migration-default，其渠道集为原 Team 渠道并集")
    void multiTeamUserKeyToMigrationDefaultWithUnionChannels() {
        runV52();

        // k1002(u2, teams 20,30) → migration-default
        Long kApp = jdbc.queryForObject(
                "SELECT application_id FROM user_api_keys WHERE id = 1002", Long.class);
        assertThat(kApp).isEqualTo(appIdByCode("migration-default"));

        // migration-default 渠道集 = teams 20,30 渠道并集 = {200,300}
        assertThat(channelsOfApp("migration-default")).isEqualTo(Set.of(200L, 300L));
    }

    @Test
    @DisplayName("无 Team 用户 Key 归 migration-default")
    void noTeamUserKeyToMigrationDefault() {
        runV52();

        Long kApp = jdbc.queryForObject(
                "SELECT application_id FROM user_api_keys WHERE id = 1003", Long.class);
        assertThat(kApp).isEqualTo(appIdByCode("migration-default"));
    }

    @Test
    @DisplayName("迁移后所有 Key 的 application_id 均已回填（无 NULL 残留）")
    void allKeysHaveApplicationId() {
        runV52();

        Long nullCount = jdbc.queryForObject(
                "SELECT COUNT(*) FROM user_api_keys WHERE application_id IS NULL", Long.class);
        assertThat(nullCount).isZero();
    }

    @Test
    @DisplayName("V52 幂等：重复执行不产生重复 applications / application_channels / 回填")
    void idempotentOnRerun() {
        // 首次执行
        runV52();

        long appCount1 = jdbc.queryForObject("SELECT COUNT(*) FROM applications", Long.class);
        long appChanCount1 = jdbc.queryForObject("SELECT COUNT(*) FROM application_channels", Long.class);
        long nullKeys1 = jdbc.queryForObject(
                "SELECT COUNT(*) FROM user_api_keys WHERE application_id IS NULL", Long.class);

        // 重复执行 V52
        runV52();

        long appCount2 = jdbc.queryForObject("SELECT COUNT(*) FROM applications", Long.class);
        long appChanCount2 = jdbc.queryForObject("SELECT COUNT(*) FROM application_channels", Long.class);
        long nullKeys2 = jdbc.queryForObject(
                "SELECT COUNT(*) FROM user_api_keys WHERE application_id IS NULL", Long.class);

        assertThat(appCount2).as("applications 不应重复插入").isEqualTo(appCount1);
        assertThat(appChanCount2).as("application_channels 不应重复插入").isEqualTo(appChanCount1);
        assertThat(nullKeys2).as("重复执行后仍无 NULL application_id").isEqualTo(nullKeys1).isZero();
    }
}
