#
# Copyright (c) 2025 codingas.com
# Licensed under the Apache License, Version 2.0.
# See the LICENSE file for details.
#

spring:
  application:
    name: gateway-cli
  shell:
    interactive:
      enabled: true

logging:
  level:
    root: INFO
    com.codingas.gateway: DEBUG
